FactoryBot.define do
  factory :article do
    # Dynamic - sequence can be searched within api references
    # Unique values in a specific format (for example, e-mail addresses) can be generated using sequences. Sequences are defined by calling sequence in a definition block, and values in a sequence are generated by calling generate:
    sequence(:title) { |n| "My Article #{n}" }
    sequence(:content) { |n| "The content #{n}" }
    sequence(:slug) { |n| "my-article #{n}" }
  end
end
